### ISSUE TITLE
Hub Mass

### ISSUE THREAD

**Issue by jsburklund** [Terabee/teraranger_description#8]
https://github.com/Terabee/teraranger_description/blob/e2db753f24aaccd401a485d0791bac1e8d7c634d/urdf/base_hub.urdf.xacro#L74

https://github.com/Terabee/teraranger_description/blob/e2db753f24aaccd401a485d0791bac1e8d7c634d/urdf/base_hub.urdf.xacro#L34

Is the mass intended to really be 300 grams?  This seems significantly more than what is quoted on the website.  Similar question for the inertia parameters. Is the mass for the inertia calculations really intended to be 100 grams?

**Comment by Babtou67** [comment]
Hello @jsburklund,

Thanks for pointing us that mistake.
We will change the value with the one from our website which are the corrects one. 

Cheers.

**Comment by pl-kabaradjian** [comment]
Hello @jsburklund ,

Mass values have been corrected and inertia added for single sensor. We didn't include frame weight as Hub Evo can be used without one.

If you have other questions related to your use case, feel free to contact our [support](https://www.terabee.com/contact).

Cheers.

**Comment by jsburklund** [comment]
The mass for the configuration with only a single hub has not been updated yet:
https://github.com/Terabee/teraranger_description/blob/2f7c325315409495879619de2a51373980b7b544/urdf/base_hub.urdf.xacro#L74

Thank you for your prompt response!

**Comment by pl-kabaradjian** [comment]
Missed that bit indeed.
Fixed now in #10

**Comment by Babtou67** [comment]
Problems resolved, i close the issue.
